name: "Build Docker Image"
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build_registry_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull docker image
        run: |
          docker pull ghcr.io/butia-bots/tmc_wrs_docker:nvidia
      - name: Build image
        run: |
          ./build.sh
      - name: Push images
        run: |
          ./push.sh   