name: "Build Docker Image"
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build_registry_image:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo pip install vcstool
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone repositories
        run: |
          vcs import --recursive < butia_minimal.repos
      - name: Build images
        run: |
          ./build.sh --chache-from ghcr.io/butia-bots/tmc_wrs_docker
      - name: Log into registry
        run: | 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        run: |
          ./push.sh   